### ISSUE TITLE
Unable to prevent network hanging if there's no internet accessible.

### ISSUE THREAD

**Issue by tvanriper** [icodealot/noaa#11]
## Steps to reproduce

1. Disconnect your computer from the internet (no WiFi, no ethernet).
2. Try to run an example or a test that attempts to reach noaa.

## Desired result

Can modify the example or test to provide a timeout so the request fails gracefully.

## Actual result

All tests and examples will hang indefinitely, ultimately failing if the test has a time limit imposed on it.

And because the code performing the network call uses http.DefaultClient, and http.DefaultClient doesn't provide a way to set a timeout value, you have no hope of allowing this to time out gracefully.

This causes problems in production environments where the internet can be spotty.

**Comment by icodealot** [comment]
Thanks for the related PR.

Closed by https://github.com/icodealot/noaa/pull/10
