### ISSUE TITLE
Can this project include AQI information?

### ISSUE THREAD

**Issue by zachfi** [icodealot/noaa#3]
I'm looking at the API docs for NOAA, but I don't see information about the payload.  https://www.ncdc.noaa.gov/cdo-web/webservices/v2  Does the API return any new information perhaps about air quality?

**Comment by AllenM90** [comment]
Based on the information here: https://weather-gov.github.io/api/gridpoints/  - it doesn't look like the weather.gov API provides Air Quality Index(AQI) information.  However, it is publicly available through a different API here: https://docs.airnowapi.org/ from the EPA via AirNow.gov.  
The weather.gov data does have information that bears on air quality.  It reports on "P-VTEC phenomenon and significance codes."  So, it will report and maybe forecast things like:  AS - Ash fall,  AS - Air stagnation, or SM - Dense Smoke.  The codes are described in this pdf: https://www.nws.noaa.gov/directives/sym/pd01017003curr.pdf .   I think you could also access the Atmospheric Dispersion Index, though the weather.gov API, but it is only one component of the AQI.  Hope that helps a bit.  Are you looking to implement an AQI data pull in Go?

**Comment by zachfi** [comment]
Thank you for the information.  Yes in Go.  I've written a couple weather exporters for wunderground and for openweathermap, to get data into Prometheus but plan to replace both of those projects with something that combines multiple sources, and this seemed like a reasonable place to start.  Though, I want to get AQI information as part of the details from the very start.  Fire season is probably on its way out where I live, but next year I'm sure it will be back.

**Comment by AllenM90** [comment]
This project may already have what you need:  https://github.com/emmaly/airnow .   It looks like it does calls for individual zip codes.  The API docs mention that if you want a large part of the data set (like state and country wide observations or forecasts), iterating zip codes is not the right answer since there are a lot more zips than monitoring locations.  They recommend downloading a file for that.  I didn't see any GITHUB projects in Go that already did that task, if you're looking to download and parse files for a larger data set, I'd be interested in contributing.

**Comment by tvanriper** [comment]
NOAA's documentation for their API is available here, mostlyl:

https://weather-gov.github.io/api/general-faqs

Or if you're familiar with the OpenAPI format, you can read their spec that way from here:  https://api.weather.gov/openapi.json ... I think the specific item you want falls under component/schemas/GridpointForecast and component/schemas/GridpointForecastPeriod.

As far as I can tell, they do not provide air quality index data.  But maybe your eyes will notice something mine doesn't.

**Comment by icodealot** [comment]
I know this is 2+ years old but... as of now no AQI. I would be willing to consider updating endpoints in this wrapper in the future if the data is eventually surfaced by NOAA.
